config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # footer pages
  get "staticpages/term", as: "footer_term"
  get "staticpages/inquire", as: "footer_inquire"
  get "staticpages/policy", as: "footer_policy"

  # by devise
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  # not devise user routes
  namespace :users do
    resources :follows, only: %i[ index create destroy ], param: :screen_name
    resources :profiles, only: %i[ show edit update ], param: :screen_name
  end
  # table: posts
  # resources :posts, param: :post_uid
  resources :posts do
    resources :comments, only: %i[ create ]
    collection do
      get :bookmarks
      get :drafts
    end
  end
  resources :bookmarks, only: %i[ create destroy ]
  resources :post_likes, only: %i[ create destroy ]
  resources :comment_likes, only: %i[ create destroy ]

  # for stimulus
  get "tags/search"
end

app/models/user.rb
class User < ApplicationRecord
  # 以下 Gem 導入に際して必要になった記述
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :timeoutable,
         :confirmable,
         :omniauthable, omniauth_providers: [ :google_oauth2 ]
  # carrierwave関連
  attr_accessor :profile_image_cache
  mount_uploader :profile_image, ProfileImageUploader

  ##############################################################################
  # REVIEW: 以下不要か？
  require "securerandom"
  # 保存前処理
  before_save :check_secure_id
  before_save :check_screen_id

  # アトリビュート
  attribute :user_uid, :string, default: -> { SecureRandom.alphanumeric(20) }
  attribute :screen_name, :string, default: -> { SecureRandom.alphanumeric }
  attribute :account_name, :string, default: "匿名さん"
  attribute :gender, :integer, default: 0
  attribute :age, :integer, default: 0
  attribute :introduction, :string, default: "よろしくお願いいたします"

  # アソシエーション
  has_many :posts

  # table: post_likes
  has_many :post_likes, dependent: :destroy
  has_many :like_posts, through: :post_likes, source: :post, dependent: :destroy

  # table: bookmarks
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post, dependent: :destroy

  # table: comments
  has_many :comments, dependent: :destroy
  # hmt型
  # ユーザーが削除されてもコメントは残す
  has_many :comment_posts, through: :comments, source: :post

  # table: comment_likes
  has_many :comment_likes, dependent: :destroy
  has_many :liked_comments, through: :comment_likes, source: :comment

  # table: follows
  has_many :follower_relationships, class_name:  "Follow",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
  has_many :followees, through: :follower_relationships, source: :followee
  has_many :followee_relationships, class_name:  "Follow",
                                    foreign_key: "followee_id",
                                    dependent: :destroy
  has_many :followers, through: :followee_relationships, source: :follower

  # バリデーション
  # devise field
  # パスワード登録時に必要な最低文字数を8文字に変更
  devise :validatable, password_length: 8..128
  # column: user_uid
  validates :user_uid, presence: true, length: { is: 20 }, uniqueness: true
  # column: screen_name
  validates :screen_name, presence: true, length: { minimum: 5, maximum: 16 }, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  # column: account_name
  validates :account_name, presence: true, length: { minimum: 1, maximum: 20 }

  # column: introduction (文字数はXの自己紹介文160文字制限仕様に倣う)
  validates :introduction, length: { maximum: 160 }, allow_blank: true

  # 列挙型
  # column: gender
  enum gender: { unknown: 0, male: 1, female: 2, other: 99 }, _prefix: true

  # column: age
  enum age: {
    unknown: 0,
                  teens: 1,
                  twenties: 2,
                  therties: 3,
                  fourties: 4,
                  fifties: 5,
                  sixties: 6,
                  morethan: 99,
                  other: 100
                }, _prefix: true


  # devise for omniauth-google-oauth2
  # https://github.com/heartcombo/devise/wiki/OmniAuth%3A-Overview
  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
    user.skip_confirmation! # メール認証のスキップ
    user.save
    user
  end

  def self.new_with_session(params, session)
    provider = "google"
    super.tap do |user|
      if data = session["devise.#{ provider }_data"] && session["devise.#{ provider }_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # URLに任意のパラメータでルーティング
  def to_param
    screen_name
  end

  private ###################################################################
    # 新規会員登録時および更新時にuser_idに重複が無いかをチェックした上で保存する
    def check_secure_id
      return if User.find_by(user_uid: self.user_uid) != nil
      # 初回設定時
      loop do
        break if User.find_by(user_uid: self.user_uid) == nil
        self.user_uid = SecureRandom.alphanumeric(20)
      end
    end

    # 新規会員登録時および更新時にscreen_idに重複が無いかをチェックした上で保存する
    def check_screen_id
      return if User.find_by(screen_name: self.screen_name) != nil
      loop do
        break if User.find_by(screen_name: self.screen_name) == nil
        self.screen_name = SecureRandom.alphanumeric
      end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/follows_controller.rb
class Users::FollowsController < ApplicationController
  # deviseによるログイン済みかの判定
  before_action :authenticate_user!
  # フォロー対象のユーザー情報を取得
  before_action :set_followee_user, only: %i[ create destroy ]

  # フォロワー一覧表示
  def index
    @followees = current_user.followees.order(created_at: :desc).page(params[:page]).per(5)
  end

  # フォロー処理
  def create
    current_user.follower_relationships.create(followee_id: @followee.id)
    flash[:notice] = t("messages.follow_info", account_name: @followee.account_name)
    redirect_to users_profile_path(@followee.screen_name)
  end

  # フォローを外す処理
  def destroy
    target_followee = current_user.follower_relationships.find_by(followee_id: @followee.id)
    target_followee.destroy
    flash[:notice] = t("messages.unfollow_info", account_name: @followee.account_name)
    redirect_to users_profile_path(@followee.screen_name), status: :see_other
  end

  private ##################################################################

    # フォロー対象のユーザー情報を取得
    def set_followee_user
      @followee = User.find_by(screen_name: params[:screen_name])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :google_oauth2

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    provider = "google"
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{ provider }") if is_navigational_format?
    else
      session["devise.#{ provider }_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  # 対象ユーザー取得
  before_action :set_user
  # deviseによるログイン済みかの判定
  before_action :authenticate_user!
  # 編集権限の確認
  before_action :is_match_login_user, only: %i[ edit update ]

  # ユーザーページを表示
  def show
    @user_posts = @user.posts.where(draft_flg: 0).includes(:tags, :post_record, :comments, :post_likes).order(created_at: :desc)
  end

  # ユーザー編集ページを表示
  def edit
  end

  # ユーザーページを更新
  def update
    if @user.update(profile_params)
      flash[:success] = t("messages.update_profile_success")
      redirect_to users_profile_path(@user.screen_name)
    else
      # screen_nameを代入しないと遷移先が指定できない問題の措置
      @user.screen_name = current_user.screen_name if @user.screen_name.blank?
      render :edit, status: :unprocessable_entity
    end
  end

  private ##############################################################
  # ユーザー本人以外がプロフィール編集しようとした場合の対策
  def is_match_login_user
    check_user = User.find_by(screen_name: params[:screen_name])
    unless check_user.blank? || check_user == current_user
      flash[:warning] = t("messages.signin_warning")
      redirect_to users_profile_path(check_user.screen_name)
    end
  end

  # 閲覧するユーザー情報
  def set_user
    @user = User.find_by(screen_name: params[:screen_name])
  end

  # プロフィールのストロングパラメータ
  def profile_params
    profile_params = params.require(:user).permit(:screen_name, :account_name, :profile_image, :profile_image_cache, :gender, :age, :introduction)

    # チェックされていれば匿名画像を適用
    check_box_val = params.require(:user)[:profile_image_flg]
    profile_params[:profile_image] = nil if check_box_val == "1"

    profile_params # return
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/follows_helper.rb
module Users::FollowsHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profiles/_follow_button.html.erb
<%= link_to t('profile.following'), users_follows_path(screen_name: user.screen_name), class: "flex items-center bg-blue-600 hover:bg-blue-700 text-gray-100 px-4 py-2 rounded text-sm space-x-2 transition duration-100", data: { turbo_method: :post }, id: "follow-btn-#{ user.screen_name }" %>

app/views/users/profiles/_form.html.erb
<%= form_with model: @user, url: users_profile_path(@user.screen_name), class: "mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl" do |f| %>
  <%# エラーメッセージ %>
  <% if @user.errors.any? %>
    <div style="color: red" class="bg-red-100 border border-gray-300 py-5 mb-6 outline-none w-full">
      <ul>
        <% @user.errors.each do |error| %>
          <li>・<%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- user_ID -->
  <div class="flex items-center">
    <%= f.label :screen_name, class: "text-lg text-gray-600" %>
    <div class="badge ml-1 bg-red-500 text-white">必須</div>
  </div>
  <span class="count text-gray-400 text-xs font-semibold">
    <%= t('profile.warning.screen_name1') %>
  </span>
  <span class="count text-gray-400 text-xs font-semibold">
    <%= t('profile.warning.screen_name2') %>
  </span>
  <%= f.text_field :screen_name,  class: "w-full bg-gray-100 border border-gray-300 p-2 mb-6 outline-none", placeholder: t('profile.placeholder.screen_name') %>

  <!-- user_name -->
  <div class="flex items-center">
    <%= f.label :account_name, class: "text-lg text-gray-600" %>
    <div class="badge ml-1 bg-red-500 text-white">必須</div>
  </div>
  <span class="count text-gray-400 text-xs font-semibold">
    <%= t('profile.warning.account_name') %>
  </span>
  <%= f.text_field :account_name,  class: "w-full bg-gray-100 border border-gray-300 p-2 mb-6 outline-none", placeholder: t('profile.placeholder.account_name') %>


  <!-- image with Preview (JS による制御) -->
  <%= f.label :profile_image, class: "text-lg text-gray-600" %>
  <span class="w-40 h-40">
    <%= f.label :profile_image, class: "mb-6" do %>
      <%= image_tag current_user.decorate.has_image?, class: "w-40 h-40  border-2 border-slate-300 rounded-full", id: "image-preview" %>
      <%= f.file_field :profile_image, class: "hidden" %>
      <%= f.hidden_field :profile_image_cache %>
    <% end %>
  </span>
  <div class="flex mt-1 mb-6">
    <%= f.check_box :profile_image_flg, class: "checkbox" %> 
    <span class="ml-1">
    <%= t('profile.not_use_image') %>
    </span>
  </div>


  <!-- introduction -->
  <%= f.label :introduction, class: "text-lg text-gray-600" %>
  <span class="count text-gray-400 text-xs font-semibold">
    <%= t('profile.warning.introduce') %>
  </span>
  <%= f.text_area :introduction, class: "w-full bg-gray-100 sec mb-6 p-3 h-60 border border-gray-300 outline-none", placeholder: t('profile.placeholder.introduce') %>

  <!-- age -->
  <div class="sm:w-full sm:mx-auto">
    <%= f.label :age, class: "text-lg text-gray-600" %>
    <%= f.select :age, User.ages_i18n.invert, {}, { class: "bg-gray-100 border border-gray-300 p-2 mb-6 outline-none" } %>
  </div>

  <!-- gender -->
  <div class="sm:w-full sm:mx-auto">
    <%= f.label :gender, class: "text-lg text-gray-600" %>
    <%= f.select :gender, User.genders_i18n.invert, {}, { class: "bg-gray-100 border border-gray-300 p-2 mb-6 outline-none" } %>
  </div>

  <!-- submit Button -->
  <div class="flex p-1 justify-end">
    <%= f.submit t('form.ok'), class: "w-3/12 p-3 bg-blue-500 text-white hover:bg-blue-400"%>
  </div>

  <!-- form_end -->
<% end %>

app/views/users/profiles/_profile_buttons.html.erb
<%# 自分以外はプロフィールの編集は不可 %>
<% if current_user == user %>
  <%= link_to edit_users_profile_path(current_user.screen_name) do %>
    <button class="flex items-center bg-blue-600 hover:bg-blue-700 text-gray-100 px-4 py-2 rounded text-sm space-x-2 transition duration-100">
        <%= image_tag 'setting.svg', class: "w-4 h-4" %>
        <span><%= t('profile.profile_edit') %></span>
    </button>
  <% end %>
<% else %>
<%# フォロー管理 %>
  <% if current_user.decorate.following?(user) %>
    <%= render "unfollow_button", user: user %>
  <% else %>
    <%= render "follow_button", user: user %>
  <% end %>
<% end %>

app/views/users/profiles/_unfollow_button.html.erb
<%= link_to t('profile.unfollowing'), users_follow_path, class: "flex items-center bg-blue-600 hover:bg-blue-700 text-gray-100 px-4 py-2 rounded text-sm space-x-2 transition duration-100", data: { turbo_method: :delete }, id: "unfollow-btn-#{user.screen_name}" %>

app/views/users/profiles/create.turbo_stream.erb
<%= turbo_stream.replace "follow-btn-#{user.id}" do %>
  <%= render 'unfollow_button', user: user %>
<% end %>

app/views/users/profiles/destroy.turbo_stream.erb
<%= turbo_stream.replace "unfollow-btn-#{user.id}" do %>
  <%= render 'follow_button', user: user %>
<% end %>

app/views/users/profiles/edit.html.erb
<% content_for :title, "Editing post" %>

<div class="mt-4">
  <%= render "form", current_user: current_user %>
</div>

app/views/users/profiles/show.html.erb
<!-- page parent -->
<div class="h-full lg:w-1/2 mx-auto p-8">
    <!-- Profile header -->
    <div class="bg-slate-100 rounded-lg shadow-xl pb-8 mb-8">
        <!-- profile header back image -->
        <div class="w-full h-[100px]"></div>
        <!-- user profile image -->
        <div class="flex flex-col items-center -mt-20">
            <!-- profile_image -->
            <% if @user.profile_image? %>
                <%= image_tag @user.profile_image.url, class: "bg-white w-40 h-40 border-4 border-white rounded-full" %>
            <% else %>
                <%= image_tag 'tokumeisan.png', class: "w-40 h-40 border-4 border-white rounded-full" %>
            <% end %>
            <!-- account_name -->
            <div class="flex items-center space-x-2 mt-4">
                <p class="text-4xl">
                    <%= @user.account_name %>
                </p>
            </div>
            <div class="flex items-center space-x-2 mt-4">
                <p class="text-xl text-slate-400">
                    <%= "＠" + @user.screen_name %>
                </p>
            </div>
            <div class="mt-4">
                <div class="flex justify-between items-center space-x-4 mt-4">
                    <p class="text-md text-slate-400">
                        <%=  t('profile.age') %>
                    </p>
                    <p class="text-md text-slate-400">
                        <%= @user.age_i18n %>
                    </p>
                </div>
                <div class="flex  justify-between items-center space-x-4 mt-4">
                    <p class="text-md text-slate-400">
                        <%=  t('profile.gender') %>
                    </p>
                    <p class="text-md text-slate-400">
                        <%= @user.gender_i18n %>
                    </p>
                </div>
                <div class="flex  justify-between items-center space-x-4 mt-4">
                    <p class="text-md text-slate-400">
                        <%=  t('profile.created_date') %>
                    </p>
                    <p class="text-md text-slate-400">
                        <%= @user.decorate.created_date %>
                    </p>
                </div>
            </div>
        </div>
        <!-- profile buttons -->
        <div class="flex-1 flex flex-col items-center lg:items-end justify-end px-8 mt-2">
            <div class="flex items-center space-x-4 mt-2">
                <%= render 'profile_buttons', user: @user %>
            </div>
        </div>
    </div>

    <!-- profile buttons -->
    <div class="mb-8 flex flex-col 2xl:flex-row space-y-4 2xl:space-y-0 2xl:space-x-4">
        <div class="flex flex-col w-full">
            <div class="flex-1 bg-slate-100 rounded-lg shadow-xl p-8">
                <h4 class="text-xl text-gray-900 font-bold">
                    <%= t('profile.introduce') %>
                </h4>
                <p class="mt-2 text-gray-700">
                    <%= @user.introduction %>
                </p>
            </div>
        </div>
    </div>
    <div class="flex-1 bg-slate-100 rounded-lg shadow-xl mb-8 p-8">
        <h4 class="text-xl text-gray-900 font-bold">
            <%= t('profile.post_info') %>
        </h4>
        <!-- ユーザーの情報 -->
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-8 mt-4">
            <!-- 投稿数 -->
            <div class="px-6 py-6 bg-gray-100 border border-gray-300 rounded-lg shadow-xl">
                <div class="flex items-center justify-between">
                    <span class="font-bold text-sm text-green-600">
                        <%= t('profile.num_posts') %>
                    </span>
                </div>
                <div class="flex items-center justify-between mt-6">
                    <div>
                        <%= image_tag 'post_edit', class: "w-12 h-12 p-2.5 bg-green-400 bg-opacity-20 rounded-full text-green-600 border border-green-600"  %>
                    </div>
                    <div class="flex flex-col">
                        <div class="flex items-end">
                            <span class="mr-1 text-2xl 2xl:text-3xl font-bold">
                                <%= @user.posts.count %>
                            </span>
                            投稿
                        </div>
                    </div>
                </div>
            </div>
            <!-- いいね数 -->
            <div class="px-6 py-6 bg-gray-100 border border-gray-300 rounded-lg shadow-xl">
                <div class="flex items-center justify-between">
                    <span class="font-bold text-sm text-red-600">
                        <%= t('profile.num_likes') %>
                    </span>
                </div>
                <div class="flex items-center justify-between mt-6">
                    <div>
                        <%= image_tag 'heart_fill', class: "w-12 h-12 p-2.5 bg-red-400 bg-opacity-20 rounded-full text-red-600 border border-red-600"  %>
                    </div>
                    <div class="flex flex-col">
                        <div class="flex items-end">
                            <span class="mr-1 text-2xl 2xl:text-3xl font-bold">
                                <%= @user.decorate.user_post_likes %>
                            </span>
                            いいね
                        </div>
                    </div>
                </div>
            </div>
            <!-- 投稿閲覧数 -->
            <div class="px-6 py-6 bg-gray-100 border border-gray-300 rounded-lg shadow-xl">
                <div class="flex items-center justify-between">
                    <span class="font-bold text-sm text-blue-600">
                        <%= t('profile.num_views') %>
                    </span>
                </div>
                <div class="flex items-center justify-between mt-6">
                    <div>
                        <%= image_tag 'post_view', class: "w-12 h-12 p-2.5 bg-blue-400 bg-opacity-20 rounded-full text-blue-600 border border-blue-600"  %>
                    </div>
                    <div class="flex flex-col">
                        <div class="flex items-end">
                            <span class="mr-1 text-2xl 2xl:text-3xl font-bold">
                                <%= @user.decorate.user_post_views %>
                            </span>
                            views
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%# 投稿一覧 %>
    <div class="px-6 mx-auto bg-slate-100 rounded-lg shadow-xl overflow-y-auto h-96">
        <div class="w-full">
            <h4 class="text-xl text-gray-900 font-bold my-6">
                <%= t('title.mypage_posts') %>
            </h4>
            <% @user_posts.each do |post| %>
                <%= render 'posts/post', post: post %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/profiles/update.html.erb
<h1>Users::Profiles#update</h1>
<p>Find me in app/views/users/profiles/update.html.erb</p>