config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # footer pages
  get "staticpages/term", as: "footer_term"
  get "staticpages/inquire", as: "footer_inquire"
  get "staticpages/policy", as: "footer_policy"

  # by devise
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  # not devise user routes
  namespace :users do
    resources :follows, only: %i[ index create destroy ], param: :screen_name
    resources :profiles, only: %i[ show edit update ], param: :screen_name
  end
  # table: posts
  # resources :posts, param: :post_uid
  resources :posts do
    resources :comments, only: %i[ create ]
    collection do
      get :bookmarks
      get :drafts
    end
  end
  resources :bookmarks, only: %i[ create destroy ]
  resources :post_likes, only: %i[ create destroy ]
  resources :comment_likes, only: %i[ create destroy ]

  # for stimulus
  get "tags/search"
end

app/models/user.rb
class User < ApplicationRecord
  # 以下 Gem 導入に際して必要になった記述
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :timeoutable,
         :confirmable,
         :omniauthable, omniauth_providers: [ :google_oauth2 ]
  # carrierwave関連
  attr_accessor :profile_image_cache
  mount_uploader :profile_image, ProfileImageUploader

  ##############################################################################
  # REVIEW: 以下不要か？
  require "securerandom"
  # 保存前処理
  before_save :check_secure_id
  before_save :check_screen_id

  # アトリビュート
  attribute :user_uid, :string, default: -> { SecureRandom.alphanumeric(20) }
  attribute :screen_name, :string, default: -> { SecureRandom.alphanumeric }
  attribute :account_name, :string, default: "匿名さん"
  attribute :gender, :integer, default: 0
  attribute :age, :integer, default: 0
  attribute :introduction, :string, default: "よろしくお願いいたします"

  # アソシエーション
  has_many :posts

  # table: post_likes
  has_many :post_likes, dependent: :destroy
  has_many :like_posts, through: :post_likes, source: :post, dependent: :destroy

  # table: bookmarks
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post, dependent: :destroy

  # table: comments
  has_many :comments, dependent: :destroy
  # hmt型
  # ユーザーが削除されてもコメントは残す
  has_many :comment_posts, through: :comments, source: :post

  # table: comment_likes
  has_many :comment_likes, dependent: :destroy
  has_many :liked_comments, through: :comment_likes, source: :comment

  # table: follows
  has_many :follower_relationships, class_name:  "Follow",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
  has_many :followees, through: :follower_relationships, source: :followee
  has_many :followee_relationships, class_name:  "Follow",
                                    foreign_key: "followee_id",
                                    dependent: :destroy
  has_many :followers, through: :followee_relationships, source: :follower

  # バリデーション
  # devise field
  # パスワード登録時に必要な最低文字数を8文字に変更
  devise :validatable, password_length: 8..128
  # column: user_uid
  validates :user_uid, presence: true, length: { is: 20 }, uniqueness: true
  # column: screen_name
  validates :screen_name, presence: true, length: { minimum: 5, maximum: 16 }, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\Z/ }
  # column: account_name
  validates :account_name, presence: true, length: { minimum: 1, maximum: 20 }

  # column: introduction (文字数はXの自己紹介文160文字制限仕様に倣う)
  validates :introduction, length: { maximum: 160 }, allow_blank: true

  # 列挙型
  # column: gender
  enum gender: { unknown: 0, male: 1, female: 2, other: 99 }, _prefix: true

  # column: age
  enum age: {
    unknown: 0,
                  teens: 1,
                  twenties: 2,
                  therties: 3,
                  fourties: 4,
                  fifties: 5,
                  sixties: 6,
                  morethan: 99,
                  other: 100
                }, _prefix: true


  # devise for omniauth-google-oauth2
  # https://github.com/heartcombo/devise/wiki/OmniAuth%3A-Overview
  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
    user.skip_confirmation! # メール認証のスキップ
    user.save
    user
  end

  def self.new_with_session(params, session)
    provider = "google"
    super.tap do |user|
      if data = session["devise.#{ provider }_data"] && session["devise.#{ provider }_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  # URLに任意のパラメータでルーティング
  def to_param
    screen_name
  end

  private ###################################################################
    # 新規会員登録時および更新時にuser_idに重複が無いかをチェックした上で保存する
    def check_secure_id
      return if User.find_by(user_uid: self.user_uid) != nil
      # 初回設定時
      loop do
        break if User.find_by(user_uid: self.user_uid) == nil
        self.user_uid = SecureRandom.alphanumeric(20)
      end
    end

    # 新規会員登録時および更新時にscreen_idに重複が無いかをチェックした上で保存する
    def check_screen_id
      return if User.find_by(screen_name: self.screen_name) != nil
      loop do
        break if User.find_by(screen_name: self.screen_name) == nil
        self.screen_name = SecureRandom.alphanumeric
      end
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/follows_controller.rb
class Users::FollowsController < ApplicationController
  # deviseによるログイン済みかの判定
  before_action :authenticate_user!
  # フォロー対象のユーザー情報を取得
  before_action :set_followee_user, only: %i[ create destroy ]

  # フォロワー一覧表示
  def index
    @followees = current_user.followees.order(created_at: :desc).page(params[:page]).per(5)
  end

  # フォロー処理
  def create
    current_user.follower_relationships.create(followee_id: @followee.id)
    flash[:notice] = t("messages.follow_info", account_name: @followee.account_name)
    redirect_to users_profile_path(@followee.screen_name)
  end

  # フォローを外す処理
  def destroy
    target_followee = current_user.follower_relationships.find_by(followee_id: @followee.id)
    target_followee.destroy
    flash[:notice] = t("messages.unfollow_info", account_name: @followee.account_name)
    redirect_to users_profile_path(@followee.screen_name), status: :see_other
  end

  private ##################################################################

    # フォロー対象のユーザー情報を取得
    def set_followee_user
      @followee = User.find_by(screen_name: params[:screen_name])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :google_oauth2

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    provider = "google"
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{ provider }") if is_navigational_format?
    else
      session["devise.#{ provider }_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  # 対象ユーザー取得
  before_action :set_user
  # deviseによるログイン済みかの判定
  before_action :authenticate_user!
  # 編集権限の確認
  before_action :is_match_login_user, only: %i[ edit update ]

  # ユーザーページを表示
  def show
    @user_posts = @user.posts.where(draft_flg: 0).includes(:tags, :post_record, :comments, :post_likes).order(created_at: :desc)
  end

  # ユーザー編集ページを表示
  def edit
  end

  # ユーザーページを更新
  def update
    if @user.update(profile_params)
      flash[:success] = t("messages.update_profile_success")
      redirect_to users_profile_path(@user.screen_name)
    else
      # screen_nameを代入しないと遷移先が指定できない問題の措置
      @user.screen_name = current_user.screen_name if @user.screen_name.blank?
      render :edit, status: :unprocessable_entity
    end
  end

  private ##############################################################
  # ユーザー本人以外がプロフィール編集しようとした場合の対策
  def is_match_login_user
    check_user = User.find_by(screen_name: params[:screen_name])
    unless check_user.blank? || check_user == current_user
      flash[:warning] = t("messages.signin_warning")
      redirect_to users_profile_path(check_user.screen_name)
    end
  end

  # 閲覧するユーザー情報
  def set_user
    @user = User.find_by(screen_name: params[:screen_name])
  end

  # プロフィールのストロングパラメータ
  def profile_params
    profile_params = params.require(:user).permit(:screen_name, :account_name, :profile_image, :profile_image_cache, :gender, :age, :introduction)

    # チェックされていれば匿名画像を適用
    check_box_val = params.require(:user)[:profile_image_flg]
    profile_params[:profile_image] = nil if check_box_val == "1"

    profile_params # return
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/follows_helper.rb
module Users::FollowsHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div role="alert" class="alert alert-error  lg:flex lg:justify-center" id="error_explanation" data-turbo-cache="false">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-6 w-6 shrink-0 stroke-current"
      fill="none"
      viewBox="0 0 24 24">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
    <div>
      <% resource.errors.full_messages.each do |message| %>
        <p>・<%= message %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class= "py-2">
    <%= link_to t(".already_sign_up"), new_session_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class= "py-2">
    <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class= "py-2">
    <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %>
  </div>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <div class= "py-2">
    <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <div class= "py-2">
    <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%= button_to user_google_oauth2_omniauth_authorize_path, form: {class: "py-6 flex justify-center"}, class: "flex items-center bg-white dark:bg-gray-900 border border-gray-300 rounded-lg shadow-md px-6 py-2 text-sm font-medium text-gray-800 dark:text-white hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500", method: :post, data: { turbo: false }  do %>
    <svg class="h-6 w-6 mr-2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="800px" height="800px" viewBox="-0.5 0 48 48" version="1.1"> <title>Google-color</title> <desc>Created with Sketch.</desc> <defs> </defs> <g id="Icons" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"> <g id="Color-" transform="translate(-401.000000, -860.000000)"> <g id="Google" transform="translate(401.000000, 860.000000)"> <path d="M9.82727273,24 C9.82727273,22.4757333 10.0804318,21.0144 10.5322727,19.6437333 L2.62345455,13.6042667 C1.08206818,16.7338667 0.213636364,20.2602667 0.213636364,24 C0.213636364,27.7365333 1.081,31.2608 2.62025,34.3882667 L10.5247955,28.3370667 C10.0772273,26.9728 9.82727273,25.5168 9.82727273,24" id="Fill-1" fill="#FBBC05"> </path> <path d="M23.7136364,10.1333333 C27.025,10.1333333 30.0159091,11.3066667 32.3659091,13.2266667 L39.2022727,6.4 C35.0363636,2.77333333 29.6954545,0.533333333 23.7136364,0.533333333 C14.4268636,0.533333333 6.44540909,5.84426667 2.62345455,13.6042667 L10.5322727,19.6437333 C12.3545909,14.112 17.5491591,10.1333333 23.7136364,10.1333333" id="Fill-2" fill="#EB4335"> </path> <path d="M23.7136364,37.8666667 C17.5491591,37.8666667 12.3545909,33.888 10.5322727,28.3562667 L2.62345455,34.3946667 C6.44540909,42.1557333 14.4268636,47.4666667 23.7136364,47.4666667 C29.4455,47.4666667 34.9177955,45.4314667 39.0249545,41.6181333 L31.5177727,35.8144 C29.3995682,37.1488 26.7323182,37.8666667 23.7136364,37.8666667" id="Fill-3" fill="#34A853"> </path> <path d="M46.1454545,24 C46.1454545,22.6133333 45.9318182,21.12 45.6113636,19.7333333 L23.7136364,19.7333333 L23.7136364,28.8 L36.3181818,28.8 C35.6879545,31.8912 33.9724545,34.2677333 31.5177727,35.8144 L39.0249545,41.6181333 C43.3393409,37.6138667 46.1454545,31.6490667 46.1454545,24" id="Fill-4" fill="#4285F4"> </path> </g> </g> </g> </svg>
    <span>Continue with Google</span>
  <% end %>
<% end %>