config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # footer pages
  get "staticpages/term", as: "footer_term"
  get "staticpages/inquire", as: "footer_inquire"
  get "staticpages/policy", as: "footer_policy"

  # by devise
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  # not devise user routes
  namespace :users do
    resources :follows, only: %i[ index create destroy ], param: :screen_name
    resources :profiles, only: %i[ show edit update ], param: :screen_name
  end
  # table: posts
  # resources :posts, param: :post_uid
  resources :posts do
    resources :comments, only: %i[ create ]
    collection do
      get :bookmarks
      get :drafts
    end
  end
  resources :bookmarks, only: %i[ create destroy ]
  resources :post_likes, only: %i[ create destroy ]
  resources :comment_likes, only: %i[ create destroy ]

  # for stimulus
  get "tags/search"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_posts_num

  # 投稿一覧を表示
  def index
    # ログイン後
    if user_signed_in?
      # 公開済みの投稿だけを取得
      published_posts = Post.where(draft_flg: 0).includes(:user)

      # ランダム
      random_posts = published_posts.order("RANDOM()").limit(@posts_num)
      @random_posts = add_blank_post(random_posts)

      # いいね数
      order_likes_ary = PostLike.group(:post_id).order("count(post_id) desc").pluck(:post_id)
      good_posts = published_posts.where(id: order_likes_ary).in_order_of(:id, order_likes_ary)
      @good_posts = add_blank_post(good_posts)

      # コメント数
      order_comments_ary = Comment.group(:post_id).order("count(post_id) desc").pluck(:post_id)
      comment_posts = published_posts.where(id: order_comments_ary).in_order_of(:id, order_comments_ary)
      @comment_posts = add_blank_post(comment_posts)

      # 最新の投稿
      latest_posts = published_posts.order(created_at: :desc).limit(@posts_num)
      @latest_posts = add_blank_post(latest_posts)
    end
  end

  private #################################
  # 投稿一覧画面で表示する投稿数
  def set_posts_num
    @posts_num = 100
  end

  # 空の投稿を追加
  def add_blank_post(posts_ary)
    diff_num = @posts_num - posts_ary.size
    result = posts_ary.to_a
    # 投稿数が@posts_numに満たない場合は空を追加
    diff_num.times do
      result.push(Post.none)
    end

    result # return
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_after_home.html.erb
  <div class="pt-5 flex w-full justify-center gap-3 fixed top-100">
    <%= link_to t('home.random_posts'), '#item1', class: "btn btn-xs", data: { turbo: false } %>
    <%= link_to t('home.good_posts'), '#item2', class: "btn btn-xs", data: { turbo: false } %>
    <%= link_to t('home.comment_posts'), '#item3', class: "btn btn-xs", data: { turbo: false } %>
    <%= link_to t('home.latest_posts'), '#item4', class: "btn btn-xs", data: { turbo: false } %>
  </div>
  <div class="container px-3 py-5 mx-auto">
    <div class="carousel w-full">
      <%# order random %>
      <div id="item1" class="pt-10 carousel-item w-full">
        <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-4">
          <% @random_posts.each do |post| %>
            <%= render 'home_posts', post: post, flg: nil %>
          <% end %>
        </div>
      </div>
      <%# order like %>
      <div id="item2" class="pt-10 carousel-item w-full">
        <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-4">
          <% @good_posts.each do |post| %>
            <%= render 'home_posts', post: post, flg: "good" %>
          <% end %>
        </div>
      </div>
      <%# order comment %>
      <div id="item3" class="pt-10 carousel-item w-full">
        <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-4">
          <% @comment_posts.each do |post| %>
            <%= render 'home_posts', post: post, flg: "comment" %>
          <% end %>
        </div>
      </div>
      <%# order latest %>
      <div id="item4" class="pt-10 carousel-item w-full">
        <div class="grid grid-cols-1 gap-8 mt-8 xl:mt-12 xl:gap-12 sm:grid-cols-2 xl:grid-cols-4 lg:grid-cols-4">
          <% @latest_posts.each do |post| %>
            <%= render 'home_posts', post: post, flg: "latest" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>

app/views/home/_before_home.html.erb
<!-- Create By Joker Banny - https://www.creative-tim.com/twcomponents/component/page-layout-responsive -->
<div class="pt-6">
  <!-- Section Hero -->
  <div class="container mx-auto h-96 rounded-md flex items-center"  style="background-image: url('<%= asset_path 'hero_image' %>')">
    <div class="sm:ml-20 text-gray-50 text-center sm:text-left">
      <h1 class="text-gray-800 text-5xl font-bold mb-4">
        エンジニアのためのアプリ開発アイデア掲示板
      </h1>
      <p class="text-gray-800 text-lg inline-block sm:block">
        今すぐアプリアイデアを投稿して、みんなの反応をみてアイデアを形にしていきましょう
      </p>
      <div class="mt-8">
        <%= link_to t('title.home.home_signup'), posts_path, class: "px-4 py-2 bg-rose-500 text-2xl rounded border border-gray-700 shadow-xl hover:bg-rose-300 hover:text-white hover:border-transparent transition ease-in duration-100" %>
      </div>
      <div class="mt-6">
        <%= link_to t('header.see_posts'), posts_path, class: "px-4 py-2 bg-cyan-500 text-2xl rounded border border-gray-700 shadow-xl hover:bg-cyan-300 hover:text-white hover:border-transparent transition ease-in duration-100" %>
      </div>
    </div>
  </div>
</div>
<!-- Section introduction -->
<main class="pt-16 container mx-auto px-6 md:px-0">
  <!-- story -->
  <section class="py-16">
    <h1 class="inline-block text-gray-600 font-bold text-3xl">
      アイデア収集所<span class="text-xl">とは？</span>
    </h1>
    <div class=" mt-10">
      <div>
        <p class="text text-gray-400">
        「なにかアプリを作ってみたい！でも、何を作ればいいのかわからない…」そんな悩みをお持ちのエンジニアの方がいらっしゃるのではないでしょうか？</br>
        多種多様なアイデアに触れるだけで意外とその悩み解決するかもしれません</br>
        開発アイデアのインスピレーションを得るために使ってみませんか？</br>
        </p>
      </div>
    </div>
  </section>

  <!-- about app -->
  <section class="py-16">
    <h1 class="inline-block text-gray-600 font-bold text-3xl">
      このアプリについて
    </h1>
    <div class="grid grid-cols-3 gap-4 mt-10">
      <div>
        <h3 class="text-lg font-semibold text-gray-500 mt-2">
          1. アプリアイデアを投稿して壁打ちできる
        </h3>
        <p class="text text-gray-400">
          あなたの投稿にコメントや反応をもらえます。その反応を参考にしてアイデアをより良いものにしていけるような機会を提供します。
        </p>
      </div>
      <div>
        <h3 class="text-lg font-semibold text-gray-500 mt-2">
          2. 投稿されたアプリアイデアに関する機能
        </h3>
        <p class="text text-gray-400">
          ブックマーク機能で投稿を保存したり、投稿者のフォロー機能、投稿の詳細検索など投稿に関する機能を充実させ情報収集しやすくしています。
        </p>
      </div>
      <div>
        <h3 class="text-lg font-semibold text-gray-500 mt-2">
          3. 引用投稿でアプリアイデアを盛り上げる
        </h3>
        <p class="text text-gray-400">
          引用機能により自分のアイデアだけでなく他のユーザーのアイデアを練ることが可能です。ご自身のアイデアと他の方とのアイデアを掛け合わせてまた違ったアイデアを創出する機会を提供します。
        </p>
      </div>
    </div>
  </section>
</main>

app/views/home/_home_posts.html.erb
<% if post.present? %>
  <%= link_to (post_path(post.post_uid)), data: { turbo: false } do %>
    <div class="w-full">
      <div class="w-full h-auto bg-slate-50 rounded-lg">
        <div class="p-2 justify-between">
          <div class="my-3">
              <p class="text-2xl text-slate-700 font-bold hover:text-gray-600 truncate">
                <%= post.title %>
              </p>
              <p class="my-3 text-gray-600 truncate">
                <%= post.content %>
              </p>
          </div>
          <% if flg == "good" %>
          <%# 表示内容の分岐-いいね %>
          <div class="flex justify-between mr-2 text-gray-700 text-sm">
            <div class="mt-6 flex">
              <%= image_tag 'heart_fill.svg', class: "w-4 h-4" %>
              <span class="ml-2">
                <%= post.post_likes.count %>
              </span>
            </div>
            <div class="flex">
              <%= image_tag post.decorate.has_image?, class: "w-10 h-10 object-cover border-2 border-slate-300 rounded-full sm:block" %>
              <div>
                <h1 class="text-gray-700 font-bold">
                  <%= post.user.account_name %>
                </h1>
                <h1 class="text-gray-400">
                  ＠<%= post.user.screen_name %>
                </h1>
              </div>
            </div>
          </div>
          <%# 表示内容の分岐-コメント %>
          <% elsif flg == "comment" %>
            <div class="flex justify-between mr-2 text-gray-700 text-sm">
              <div class="mt-6 flex">
                <%= image_tag 'comment.svg', class: "w-4 h-4" %>
                <span class="ml-2">
                  <%= post.comments.count %>
                </span>
              </div>
              <div class="flex">
                <%= image_tag post.decorate.has_image?, class: "w-10 h-10 object-cover border-2 border-slate-300 rounded-full sm:block" %>
                <div>
                  <h1 class="text-gray-700 font-bold">
                    <%= post.user.account_name %>
                  </h1>
                  <h1 class="text-gray-400">
                    ＠<%= post.user.screen_name %>
                  </h1>
                </div>
              </div>
            </div>
          <%# 表示内容の分岐-最新投稿 %>
          <% elsif flg == "latest" %>
            <div class="flex justify-between mr-2 text-gray-700 text-sm">
              <div class="mt-6 flex">
                <span class="text-xs">
                  <%= post.decorate.created_date %>
                </span>
              </div>
              <div class="flex">
                <%= image_tag post.decorate.has_image?, class: "w-10 h-10 object-cover border-2 border-slate-300 rounded-full sm:block" %>
                <div>
                  <h1 class="text-gray-700 font-bold">
                    <%= post.user.account_name %>
                  </h1>
                  <h1 class="text-gray-400">
                    ＠<%= post.user.screen_name %>
                  </h1>
                </div>
              </div>
            </div>
          <% else %>
            <div class="flex justify-end mr-2 text-gray-700 text-sm">
              <div class="flex">
                <%= image_tag post.decorate.has_image?, class: "w-10 h-10 object-cover border-2 border-slate-300 rounded-full sm:block" %>
                <div>
                  <h1 class="text-gray-700 font-bold">
                    <%= post.user.account_name %>
                  </h1>
                  <h1 class="text-gray-400">
                    ＠<%= post.user.screen_name %>
                  </h1>
                </div>
              </div>
            </div>
          <% end %>
          <%# 表示内容の分岐-END %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="w-full">
    <div class="w-full h-auto bg-slate-50 rounded-lg">
      <div class="p-2 justify-between">
        <div class="my-3">
            <p class="text-2xl text-slate-700 font-bold hover:text-gray-600 truncate">
            </p>
            <p class="my-3 text-gray-600 truncate">
            </p>
        </div>
        <div class="mt-6 flex justify-end">
          <div>
            <h1 class="text-gray-700 font-bold">
            </h1>
            <h1 class="text-gray-400">
            </h1>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <% content_for :title, "#{t('title.app')}" %>
  <%= render 'after_home' %>
<% else %> 
  <% content_for :title, "#{t('title.app')} | home" %>
  <%= render 'before_home' %>
<% end %> 