config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # footer pages
  get "staticpages/term", as: "footer_term"
  get "staticpages/inquire", as: "footer_inquire"
  get "staticpages/policy", as: "footer_policy"

  # by devise
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  # not devise user routes
  namespace :users do
    resources :follows, only: %i[ index create destroy ], param: :screen_name
    resources :profiles, only: %i[ show edit update ], param: :screen_name
  end
  # table: posts
  # resources :posts, param: :post_uid
  resources :posts do
    resources :comments, only: %i[ create ]
    collection do
      get :bookmarks
      get :drafts
    end
  end
  resources :bookmarks, only: %i[ create destroy ]
  resources :post_likes, only: %i[ create destroy ]
  resources :comment_likes, only: %i[ create destroy ]

  # for stimulus
  get "tags/search"
end

app/models/post.rb
class Post < ApplicationRecord
  # carrierwave
  mount_uploaders :images, ImageUploader

  # アソシエーション
  # table: users
  belongs_to :user
  # table: quote_relations
  has_many :quote_relations, class_name: "QuoteRelation",
                             foreign_key: "post_id",
                             dependent: :destroy
  has_many :quote_posts, through: :quote_relations, source: :quote_post
  has_many :quoted_relations, class_name: "QuoteRelation",
                             foreign_key: "quote_post_id",
                             dependent: :destroy
  has_many :quoted_posts, through: :quoted_relations, source: :quote_post

  # table: bookmarks
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post
  # table: comments
  has_many :comments, dependent: :destroy
  # table: post_genres
  has_many :post_likes, dependent: :destroy
  has_many :liked_users, through: :post_likes, source: :user
  # table: post_genres
  belongs_to :post_genre
  # column: post_tags, tags
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  # table: post_records
  has_one :post_record, dependent: :destroy

  # バリデーション
  # column: post_uid
  validates :post_uid, presence: true, length: { is: 16 }, uniqueness: true
  # column: images
  validates :images, presence: true, allow_blank: true
  # validate :image_type
  validate :image_size
  validate :image_length
  # column: title
  validates :title, presence: true, length: { minimum: 1, maximum: 50 }
  # column: content
  validates :content, presence: true, length: { minimum: 1, maximum: 500 }

  # 列挙型
  # column: post_genre
  enum post_genre_id: {
                        funny:             1,
                        technology:        2,
                        entertainment:     3,
                        game:              4,
                        lifestyle:         5,
                        business:          6,
                        art:               7,
                        history_geography: 8,
                        social:            9,
                        ideology:         10,
                        hobby:            11,
                        development:      12,
                        sports:           13,
                        music:            14,
                        travel:           15,
                        other:            16
                      }, _prefix: true
  # column: draft_flg
  enum draft_flg: { publish: 0, draft: 1 }, _prefix: true


  # URL の :id の部分に id 以外を指定
  def to_param
    post_uid
  end

  private ################################################################
  # ポストに添付するファイルの総数のバリデーション
  # ファイルサイズについての制限
  def image_size
    images.each do |image|
      if image.size > 5.megabytes
        errors.add(:images, "は1つのファイル5MB以内にしてください")
      end
    end
  end
  # ファイル数についての制限
  def image_length
    if images.length > 3
      errors.add(:images, "は 3 枚以内にしてください")
    end
  end

  # タグの入力内容の保存前修正
  def modify_tag_name
    before_str = "０-９ａ-ｚＡ-Ｚ"
    after_str = "0-9a-zA-Z"
    # 全角を半角に変換＆小文字を大文字に変換
    self.name = name.tr(before_str, after_str).upcase if name.present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # 対象ポストの取得
  before_action :set_post, only: %i[ show edit update destroy ]
  # 検索パラメータの取得
  before_action :set_q_order, only: %i[ index ]
  # deviseによるログイン済みかの判定
  before_action :authenticate_user!, except: %i[ index ]
  # 編集権限の確認
  before_action :is_match_login_user, only: %i[ edit update destroy ]

  # 投稿検索結果画面
  # デフォルトは全件表示
  def index
    # フラグ無し
    @posts = Post.where(draft_flg: 0).includes(:tags, :post_record, :comments, :post_likes, :user).order(created_at: :desc).page(params[:page]).per(10)

    # 検索なら検索を実行
    if params[:q].present? && params[:q][:search_flg].present?
      # 検索時
      @posts = PostSearchForm.new(search_post_params).search.page(params[:page]).per(10)
    end
  end

  # 投稿詳細画面表示
  def show
    # ビューをカウント
    postRecord = PostRecord.find_by(post_id: @post)
    postRecord.countup_view unless postRecord.blank?
    # コメントフォーム用
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  # 新規投稿画面表示
  def new
    @post = Post.new
    @quote_post = Post.find_by(post_uid: params[:quote_post_id])
    # 引用投稿か否か
    if !!(@quote_post)
      @quote_post.quote_relations.new
    end
  end

  # 投稿編集画面表示
  def edit; end

  # 投稿登録処理処理
  def create
    # 親クラスからインスタンスを取得しレコードを生成
    @post = get_post_genre.posts.build(post_params)
    # 引用投稿のパラメータ
    quote_post_param = params.require(:post)[:quote_post]
    # 引用投稿した投稿の取得
    @quote_post = Post.find(quote_post_param) if quote_post_param
    # 投稿に設定しているタグの取得
    @post_tags = modify_post_tags

    if @post.save
      # ジャンルの設定
      @post.create_post_record(post_id: @post.id)
      # 引用先の設定
      @post.quote_posts << @quote_post if @quote_post
      # 投稿のタグ設定
      register_article_tags(@post, @post_tags) if @post_tags

      flash[:success] = t("messages.post_success")
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # 投稿更新処理
  def update
    # ジャンルの更新
    @post.post_genre = get_post_genre
    # 投稿に設定しているタグの取得
    @post_tags = modify_post_tags

    if @post.update(update_params)
      # 投稿のタグ設定
      register_article_tags(@post, @post_tags) if @post_tags
      flash[:success] = t("messages.update_post_success")
      redirect_to post_path(@post.post_uid)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # 投稿削除処理
  def destroy
    @post.destroy!
    flash[:success] = t("messages.destroy_post_success")
    redirect_to posts_path, status: :see_other
  end

  # ブックマークした投稿のみを一覧表示
  def bookmarks
    @bookmark_posts = current_user.bookmark_posts.order(created_at: :desc).page(params[:page]).per(10)
  end

  # 下書き投稿のみを一覧表示
  def drafts
    @draft_posts = Post.where(draft_flg: 1, user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(10)
  end

  private ###################################################################
    # 対象の投稿の取得
    def set_post
      @post = Post.find_by(post_uid: params[:id])
    end

    # 投稿者本人以外が操作しようとした場合の対策
    def is_match_login_user
      posted_user = Post.find_by(post_uid: params[:id]).user
      redirect_to post_path(@post) unless posted_user.blank? || posted_user == current_user
    end

    # 検索時のパラメータの並び替えの選択肢を渡す
    def set_q_order
      @q_order = {
                    "最新順": "latest",
                    "古い順": "oldest",
                    "いいね数": "post_likes",
                    "コメント数": "post_comments"
                 }
    end

    # 検索時のパラメータ取得
    def search_post_params
      params[:q].permit(:post_genre_id, :how_order, :contents, :tags)
    end

    # params から post_genre の id を割り出す
    def get_post_genre
      post_genre_sym = params.require(:post)[:post_genre_id].to_sym
      get_post_genre_id = Post.post_genre_ids[post_genre_sym]
      PostGenre.find(get_post_genre_id)
    end

    # 投稿内容のストロングパラメータ
    def post_params
      params.require(:post).permit(:title, :content, { images: [] }, :images_cache, :draft_flg).merge(post_uid: gen_secure_id, user_id: current_user.id)
    end

    # 新規会員登録時、post_idに重複が無いかをチェックした上で保存する
    def gen_secure_id
      loop do
        gen_uid = SecureRandom.alphanumeric
        return gen_uid if Post.find_by(post_uid: gen_uid) == nil
      end
    end

    # 更新対象のカラムのみ
    def update_params
      update_params = params.require(:post).permit(:title, :content, { images: [] }, :remove_images, :draft_flg)
      # アップロードされた画像がある場合
      new_images_ary = update_params[:images].select { |image| image.class == ActionDispatch::Http::UploadedFile }
      # 新規にアップロードされた画像だけを投稿画像とする
      update_params[:images] = new_images_ary if new_images_ary.present?
      # チェックボックスに応じて投稿画像を削除する
      update_params[:images] = nil if update_params[:remove_images] === 1
      update_params # return
    end

    # 投稿のタグを登録用に加工する
    # tagifyで`,`区切りにしているためここで分割
    def modify_post_tags
      if params[:post][:input_post_tags].present?
        tags = params[:post][:input_post_tags].split(",").uniq
      end
    end

    # タグの登録前
    def register_article_tags(post, tags)
      # 一旦該当投稿のタグを全て削除
      post.tags.destroy_all
      # 登録済みのタグがあればそれを登録、なければ新規作成し投稿に関連付け
      tags.each do |tag|
        tag = Tag.find_or_create_by(name: tag)
        post.tags << tag
      end
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_bookmark.html.erb
<%= link_to (post_path(post.post_uid)), class: 'list-content', data: { turbo: false } do %>
  <div class="mx-auto max-w-4xl px-10 my-2 py-6 bg-white rounded-lg shadow-md">
    <div class="lg:flex justify-between items-center">
        <span class="font-light text-gray-600">
          <%= post.decorate.created_date %>
        </span>
        <p class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500">
          <%= post.post_genre_id_i18n %>
        </p>
    </div>
    <div class="mt-2 flex justify-end items-center">
        <p class="px-2 py-1 bg-red-600 text-gray-100 font-bold rounded hover:bg-gray-500">
          <%= 'TODO: タグ' %>
        </p>
    </div>
    <div class="mt-2">
        <p class="text-2xl text-gray-700 font-bold hover:text-gray-600 truncate">
          <%= post.title %>
        </p>
        <p class="mt-2 text-gray-600 truncate">
          <%= post.content %>
        </p>
    </div>
    <div class="lg:flex justify-between items-center mt-4">
      <div class="m-4 flex items-center">
        <!-- icons -->
        <div class="flex mr-2 text-gray-700 text-sm mr-8">
          <%= image_tag 'post_view.svg', class: "w-4 h-4" %>
          <span class="ml-2">
            <%= post.post_record.view_count %>
          </span>
        </div>
        <div class="flex mr-2 text-gray-700 text-sm mr-8">
          <%= image_tag 'post_view.svg', class: "w-4 h-4" %>
          <span class="ml-2">
            <%= post.post_record.view_count %>
          </span>
        </div>
        <div class="flex mr-2 text-gray-700 text-sm mr-8">
          <%= image_tag 'post_view.svg', class: "w-4 h-4" %>
          <span class="ml-2">
            <%= post.post_record.view_count %>
          </span>
        </div>
      </div>
      <div>
        <%= link_to users_profile_path(post.user.screen_name), class:"lg:flex items-center", data: { turbo: false } do %>
          <div class="flex">
              <%= image_tag post.decorate.has_image?, class: "mx-4 w-10 h-10 object-cover border-2 border-slate-300 rounded-full sm:block" %>
            <div>
              <h1 class="text-gray-700 font-bold">
                <%= post.user.account_name %>
              </h1>
              <h1 class="text-gray-400">
                ＠<%= post.user.screen_name %>
              </h1>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_bookmark_buttons.html.erb
<% if current_user.decorate.bookmark?(post) %>
  <%= render 'bookmarks/unbookmark', { post: post } %>
<% else %>
  <%= render 'bookmarks/bookmark', { post: post } %>
<% end %>

app/views/posts/_comment_card.html.erb
<% if comment.user_id == post.user_id %>
<%# 投稿者以外からのコメント %>
  <div id="comment-<%= comment.id %>" class="chat chat-start">
    <div class="chat-image avatar">
      <div class="w-10 rounded-full">
        <%= link_to users_profile_path(comment.user) do %>
          <%= image_tag comment.decorate.comment_user_image %>
        <% end %>
      </div>
    </div>
    <div class="chat-header">
      <%= link_to users_profile_path(comment.user) do %>
        <p class="text-xs">
          <%= comment.decorate.get_account_name %>
        </p>
        <p class="text-xs text-slate-400">
          ＠<%= comment.decorate.get_screen_name %>
        </p>
      <% end %>
    </div>
    <div class="chat-bubble break-words">
      <%= comment.content %>
    </div>
    <%# コメントへのいいね %>
    <%= render 'comment_like_buttons', { comment: comment } %>
    <div class="chat-footer opacity-50">
      <%= comment.decorate.created_date %>
      <%# コメント削除ボタン %>
      <% if comment.user_id == post.user_id %>
        <%#= link_to "[削除]", post_comment_path(post.post_uid, comment), data: { turbo_method: :delete } %>
      <% end %>
    </div>
  </div>
<% else %>
<%# 投稿者本人のコメント %>
  <div id="comment-<%= comment.id %>" class="chat chat-end">
    <div class="chat-image avatar">
      <div class="w-10 rounded-full">
        <%= link_to users_profile_path(comment.user) do %>
          <%= image_tag comment.decorate.comment_user_image %>
        <% end %>
      </div>
    </div>
    <div class="chat-header break-words">
      <%= link_to users_profile_path(comment.user) do %>
        <p class="text-xs">
          <%= comment.decorate.get_account_name %>
        </p>
        <p class="text-xs text-slate-400">
          ＠<%= comment.decorate.get_screen_name %>
        </p>
      <% end %>
    </div>
    <div class="chat-bubble">
      <%= comment.content %>
      <%# コメント削除ボタン %>
      <% if comment.user_id == post.user_id %>
        <%#= link_to "[削除]", post_comment_path(post.post_uid, comment), data: { turbo_method: :delete } %>
      <% end %>
    </div>
    <%# コメントへのいいね %>
    <%= render 'comment_like_buttons', { comment: comment } %>
    <div class="chat-footer opacity-50">
      <%= comment.decorate.created_date %>
    </div>
  </div>
<% end %>

app/views/posts/_detail_post.html.erb
<!-- header -->
<div class="flex justify-between">
  <%= link_to users_profile_path(post.user), class: "flex space-x-4 items-center" do %>
    <div class="w-12 h-12">
      <%= image_tag post.user.decorate.has_image?, class: "rounded-full w-full h-full object-cover" %>
    </div>
    <div class="space-y-2">
      <div class="flex space-x-2 items-center">
        <h2 class="text-base"><%= post.user.account_name %></h2>
        <div class="text-xs">＠<%= post.user.screen_name %></div>
      </div>
      <p class="text-xs"><%= post.decorate.created_date %></p>
    </div>
  <% end %>
  <%= link_to new_post_path(quote_post_id: post.post_uid), class:"p-1 my-auto border border-slate-400 rounded-2xl align-center" do %>
    <%= image_tag 'quote_post', class: "mx-auto w-4 h-4" %>
    <p class="text-xs">quote</p>
  <% end %>
</div>

<!--post genre-->
<div>
  <span class="mb-3 px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500">
    <%= post.post_genre_id_i18n %>
  </span>
</div>

<!--content-->
<div>
  <p class="mb-3 text-2xl leading-6">
    <%= post.title %>
  </p>
  <p class="text-sm leading-6 break-words">
    <%= post.content %>
  </p>
</div>

<!-- image grid-->
<div class="grid grid-cols-6 col-span-2  gap-2">
  <% post.images.each.with_index(1) do |image, index| %>
    <div class="relative overflow-hidden rounded-xl col-span-2 max-h-[10rem]">
      <%= render 'image_modal', image: image, index: index %>
    </div>
  <% end %>
</div>

<!--post genre-->
<% if post.tags.present? %>
  <ul>
    <li>
      ＃タグ
    </li>
    <% post.tags.each do |tag| %>
      <li>
        <%= link_to posts_path( q: { tags: tag.name, search_flg: true } ), class:"link link-info" do %>
          <%= tag.name %>
        <% end %>
      </li>
    <% end %>
</ul>
<% end %>

<!-- post info-->
  <div class="h-16 border-b flex items-center justify-around">
    <div class="flex items-center">
      <div class="text-sm	"><%= post.comments.count %> コメント</div>
    </div>
    <div class="flex items-center">
      <%= render 'like_buttons', { post: post } %>
    </div>
    <div class="flex items-center">
      <%= render 'bookmark_buttons', { post: post } %>
    </div>
    <div class="flex items-center">
      <%= render 'shared/x_share', { post: post } %>
    </div>
  </div>
</div>

app/views/posts/_image_modal.html.erb
<!-- Open the modal using ID.showModal() method -->
<button class="h-full w-full object-cover" onclick="my_modal_<%= "#{ index }" %>.showModal()">
  <%= image_tag image.url, class: "h-full w-full object-cover", alt: "投稿の画像" %>
</button>
<dialog id="my_modal_<%= "#{ index }" %>" class="modal">
  <div class="modal-box flex justify-center">
    <%= image_tag image.url, class: "h-auto w-auto", alt: "アプリアイコン" %>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button></button>
  </form>
</dialog>

app/views/posts/_post.html.erb
<div class="mx-auto max-w-4xl px-10 my-2 py-6 bg-white rounded-lg shadow-md">
  <%= link_to (post_path(post.post_uid)), class: 'list-content', data: { turbo: false } do %>
    <div class="lg:flex justify-between items-center">
        <span class="font-light text-gray-600">
          <%= post.decorate.created_date %>
        </span>
        <p class="px-2 py-1 bg-gray-600 text-gray-100 font-bold rounded hover:bg-gray-500">
          <%= post.post_genre_id_i18n %>
        </p>
    </div>
    <div class="mt-2 lg:flex justify-end items-center">
    <!--post genre-->
    <% if post.tags.present? %>
      <% post.tags.each do |tag| %>
        <div class="ml-2 link link-info">
          #<%= tag.name %>
        </div>
      <% end %>
    <% end %>
    </div>
    <div class="mt-2">
        <p class="text-2xl text-gray-700 font-bold hover:text-gray-600 truncate">
          <%= post.title %>
        </p>
        <p class="mt-2 text-gray-600 truncate">
          <%= post.content %>
        </p>
    </div>
    <div class="lg:flex justify-between items-center mt-4">
      <div class="m-4 flex items-center">
        <!-- icons -->
        <div class="flex mr-2 text-gray-700 text-sm mr-8">
          <%= image_tag 'post_view.svg', class: "w-4 h-4" %>
          <span class="ml-2">
            <%= post.post_record.view_count %>
          </span>
        </div>
        <div class="flex mr-2 text-gray-700 text-sm mr-8">
          <%= image_tag 'comment.svg', class: "w-4 h-4" %>
          <span class="ml-2">
            <%= post.comments.count %>
          </span>
        </div>
        <div class="flex mr-2 text-gray-700 text-sm mr-8">
          <%= image_tag 'heart_fill.svg', class: "w-4 h-4" %>
          <span class="ml-2">
            <%= post.post_likes.count %>
          </span>
        </div>
      </div>
      <div>
        <%#  %>
        <%#= link_to users_profile_path(post.user.screen_name), class:"lg:flex items-center", data: { turbo: false } do %>
          <div class="flex">
              <%= image_tag post.decorate.has_image?, class: "mx-4 w-10 h-10 object-cover border-2 border-slate-300 rounded-full sm:block" %>
            <div>
              <h1 class="text-gray-700 font-bold">
                <%= post.user.account_name %>
              </h1>
              <h1 class="text-gray-400">
                ＠<%= post.user.screen_name %>
              </h1>
            </div>
          </div>
        <%# end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_quote_post.html.erb
<%= link_to (post_path(post)), class: 'list-content', data: { turbo: false } do %>
  <div class="mx-auto max-w-4xl px-10 my-2 py-6 bg-white border-2 border-cyan-400 rounded-lg shadow-md">
    <div class="mt-2">
        <span class="px-2 py-1 bg-cyan-600 text-gray-100 font-bold rounded">
          <%= t('posts.show.quote') %>
        </span>
        <p class="mt-2 text-2xl text-gray-700 font-bold hover:text-gray-600 truncate">
          <%= post.title %>
        </p>
        <p class="mt-2 text-gray-600 truncate">
          <%= post.content %>
        </p>
    </div>
    <div class="lg:flex justify-between items-center mt-4">
      <div>
        <%= link_to users_profile_path(post.user.screen_name), class:"lg:flex items-center", data: { turbo: false } do %>
          <div class="flex">
              <%= image_tag post.decorate.has_image?, class: "mx-4 w-10 h-10 object-cover border-2 border-slate-300 rounded-full sm:block" %>
            <div>
              <h1 class="text-gray-700 font-bold">
                <%= post.user.account_name %>
              </h1>
              <h1 class="text-gray-400">
                ＠<%= post.user.screen_name %>
              </h1>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/bookmarks.html.erb
<% content_for :title, t('title.bookmarks')  %>

<!-- title -->
<div class="heading text-center font-bold text-2xl m-5 text-gray-800 bg-white"><%= t('title.bookmarks') %></div>

<!-- Posts layouts -->
<div class="px-6 py-10 mx-auto">
  <div class="w-full">
    <!-- Posts start -->
<%= turbo_frame_tag "bookmark_posts-page-#{@bookmark_posts.current_page}" do %>
    <%# 今のページで取得したTweet一覧 %>
  <%= render partial: "post", collection: @bookmark_posts %>

    <%# 遅延読み込みで次ページを取得する`<turbo-frame>` %>
  <%= turbo_frame_tag "bookmark_posts-page-#{@bookmark_posts.next_page}", loading: :lazy, src: path_to_next_page(@bookmark_posts) %>
<% end %>
    <!-- Posts end -->
  </div>
</div>
  <!-- Posts layouts end -->

app/views/posts/edit.html.erb
<% content_for :title, t('title.post.edit') %>

<!-- title -->
<div class="heading text-center font-bold text-2xl m-5 text-gray-800 bg-white"><%= t('title.post.edit') %></div>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<!-- タブタイトル -->
<% content_for :title, @post.title %>

<%# OGP用 %>
<% set_meta_tags title: @post.title, description: @post.content %>


<%# 投稿の表示部分 %>
<% if @post.decorate.post_status? %>
  <!-- 下書きアラート -->
  <div class="flex justify-center items-center m-1 font-medium py-1 px-2 bg-white rounded-md text-yellow-700 bg-yellow-100 border border-yellow-300 ">
      <div slot="avatar">
          <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-info w-5 h-5 mx-2">
              <circle cx="12" cy="12" r="10"></circle>
              <line x1="12" y1="16" x2="12" y2="12"></line>
              <line x1="12" y1="8" x2="12.01" y2="8"></line>
          </svg>
      </div>
      <div class="max-w-full flex-initial">
          <div class="py-2">
              <p class="text-xl font-base font-normal">
                <%= t('.draft_info') %>
              </p>
              <p class="mt-1 text-sm font-base">
                <%= t('.draft_info_sub') %>
              </p>
          </div>
      </div>
  </div>
<% end %>

<% if @post.decorate.post_owner?(current_user) %>
  <div class="pt-4 mx-auto flex justify-center items-center gap-4">
    <!-- 編集ボタン -->
    <%= link_to edit_post_path(@post.post_uid) do %>
    <button class="btn btn-active btn-primary">
      <%= t('.edit_post') %>
    </button>
    <% end %>
    <!-- 削除ボタン -->
    <%= button_to t('.delete_post'), @post, class: "btn btn-active btn-neutral", method: :delete, data: { turbo_confirm: t('.delete_confirm') } %>
  </div>
<% end %>

<!-- quote post -->
<% if @post.decorate.has_quote_post?(@post) %>
  <%= render 'quote_post', post: @post.decorate.get_quote_post(@post) %>
<% end %>

<!-- post detail -->
<div class="pt-4">
  <!-- post card -->
  <div class="rounded-lg w-full mx-5 md:w-[40rem] mx-auto">
  <%= t('.post_views') %>
  <%= @post.post_record.view_count %>
  </div>
  <div class="bg-slate-100 rounded-lg w-full mx-5 md:w-[40rem]  space-y-6 p-10 mx-auto">
    <%= render 'detail_post', post: @post %>
  </div>

  <!-- post comments -->
  <%= turbo_frame_tag "comments-list", data: { turbo_action: :advance } do %>
    <div class="bg-slate-100 rounded-lg w-full mx-5 md:w-[40rem] space-y-6 px-5 mx-auto">
      <!-- comment form -->
      <%# 下書きの場合コメントフォームは非表示 %>
      <% if !@post.decorate.post_status? %>
        <%= form_with model: [@post, @comment], class: "flex items-center justify-between", html: { data: { turbo_frame: "comments-list"} } do |f| %>
          <%= image_tag current_user.decorate.has_image?, class: "bg-white rounded-full w-10 h-10 object-cover border" %>
          <div class="flex items-center	justify-between	bg-gray-50 h-11 w-11/12 border rounded-2xl overflow-hidden px-4">
            <%= f.text_field :content, 
                class:"h-full w-full bg-gray-50 outline-none",
                minlength: "1", 
                maxlength: "140", 
                placeholder: t('form.post.post_comment') 
            %>
          </div>
          <%= f.submit 'OK', 
              class: "py-3 w-12 bg-blue-500 text-white hover:bg-blue-400 rounded-full"
          %>
        <% end %>
      <% end %>
      <%# コメント作成成功時はフラッシュメッセージ表示 %>
      <% if flash[:comment_success].present? %>
        <%= render 'shared/success_notice', message: flash[:comment_success] %>
      <% end %>
      <%# コメント一覧 %>
      <% @comments.each do |comment| %>
        <%= render 'comments/comment_card', post: @post, comment: comment %>
      <% end %>
    </div>
  <% end %>
</div>